server:
  port: 9090

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/tracker_dev?user=tracker&useSSL=false&useTimezone=true&serverTimezone=UTC&useLegacyDatetimeCode=false"

management:
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      showdetails:   HEALTH_SHOWDETAILS

welcome:
  message: "hello from gradle"
